### ISSUE TITLE
Options defaults to port=80 for SSL connections

### ISSUE THREAD

**Issue by bloodgain** [ibmmaximorestjsonapis/maximorestclient#5]
If `https()` is called on an `Options` object, but `port(num)` is not called, the `Options` object retains the default value of `80` for the instance variable `port`. This should probably default to `443` for SSL-encrypted connections.

However, `https()` should not override the value set by `port(num)`, even if `port` has been set to the value 80 by such a call.

Defaulting to 80 for SSL-encrypted connections is likely to lead to occurrences of `java.net.ConnectException: Connection refused` that have an unclear cause.

**Comment by ibmmaximorestjsonapis** [comment]
Thanks for the feedback, the issue has been fixed by remove default port. It has been delivered to Github as well as mvn rep

**Comment by bloodgain** [comment]
Oh, that's a smart fix! Thanks!

You probably want to add the `port != null` check to `getPublicURI`. It looks like `port` could be null there and create some bad URIs.

(I'd offer up suggested fixes via pull requests, but unfortunately company policy is a lot more flexible about _reporting_ issues than fixing them. So thank you for following up on these!)
