### ISSUE TITLE
MaximoConnector should log URIs sooner when debug mode set.

### ISSUE THREAD

**Issue by bloodgain** [ibmmaximorestjsonapis/maximorestclient#6]
When in debug mode, `MaximoConnector` does not always log URIs that it attempts to access before accessing them.

For example, in `connect()`, the URI is not logged until after `con.getResponseCode()` is called. However, `con.getResponseCode()` can throw connection errors if the URI is invalid (e.g. incorrect port). This can make it difficult for a Maximo REST client library user to debug the issue.

**Comment by ibmmaximorestjsonapis** [comment]
Thanks for the feedback, the issue has been fixed by logging uri before we get responsecode.
